# Generated by Django 2.2 on 2023-10-27 13:56

import apps.home.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_cat', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_con', models.CharField(max_length=30)),
                ('dure_con', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Corps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_cr', models.CharField(max_length=25)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_dep', models.CharField(max_length=25)),
                ('description', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Diplome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_dip', models.CharField(max_length=25)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Domaine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_dom', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fonction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fc', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_classe', models.CharField(max_length=1, validators=[apps.home.models.validate_digit_1_to_3])),
                ('num_echellon', models.CharField(max_length=1, validators=[apps.home.models.validate_digit_1_to_3])),
            ],
        ),
        migrations.CreateModel(
            name='Mention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_me', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Situation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_st', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='TypeConge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_tc', models.CharField(max_length=40)),
                ('nb_jour', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_en', models.CharField(max_length=30)),
                ('prenom_en', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('adress', models.TextField(default='Maninday')),
                ('sex', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('num_tel', models.CharField(max_length=10, null=True, validators=[apps.home.models.num_tel_validator])),
                ('cin', models.CharField(max_length=12, null=True, unique=True, validators=[apps.home.models.cin_validator])),
                ('indice', models.CharField(max_length=6, null=True, validators=[apps.home.models.indice_validator])),
                ('im', models.CharField(max_length=6, unique=True)),
                ('date_nais', models.DateField()),
                ('date_PF', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='enseignant_images/')),
                ('corps', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Corps')),
                ('departement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Departement')),
                ('diplome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Diplome')),
                ('domaine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Domaine')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Grade')),
                ('mention', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Mention')),
                ('situation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Situation')),
            ],
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_em', models.CharField(max_length=30)),
                ('prenom_em', models.CharField(max_length=30)),
                ('age', models.PositiveSmallIntegerField()),
                ('adresse', models.TextField(default='Maninday')),
                ('sex', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('im', models.CharField(max_length=6, unique=True)),
                ('date_nais', models.DateField()),
                ('date_PF', models.DateField(blank=True, null=True)),
                ('cin', models.CharField(max_length=12, unique=True)),
                ('num_tel', models.CharField(max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='employe_photos/')),
                ('indice', models.CharField(max_length=6)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Categorie')),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Contrat')),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Departement')),
                ('diplome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Diplome')),
                ('domaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Domaine')),
                ('fonction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Fonction')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Grade')),
                ('situation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Situation')),
            ],
            options={
                'verbose_name': 'Employé',
                'verbose_name_plural': 'Employés',
            },
        ),
        migrations.CreateModel(
            name='Conge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('jours_utilises', models.PositiveIntegerField(null=True)),
                ('jours_restants', models.PositiveIntegerField(null=True)),
                ('employe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Employe')),
                ('enseignant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Enseignant')),
                ('type_conge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.TypeConge')),
            ],
        ),
        migrations.CreateModel(
            name='Avancement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_av', models.DateField()),
                ('employe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Employe')),
                ('enseignant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Enseignant')),
                ('grade_av', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Grade')),
            ],
        ),
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_aff', models.DateField()),
                ('motif', models.TextField()),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Employe')),
                ('n_departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Departement')),
                ('n_domaine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Domaine')),
                ('n_fonction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Fonction')),
            ],
            options={
                'ordering': ['-date_aff'],
            },
        ),
    ]
