# Generated by Django 2.2 on 2023-10-30 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20231029_0906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affectation',
            options={},
        ),
        migrations.AlterField(
            model_name='categorie',
            name='num_cat',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='corps',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='departement',
            name='description',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='diplome',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employe',
            name='fonction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Fonction'),
        ),
        migrations.AlterField(
            model_name='mention',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
