# Generated by Django 2.2 on 2023-11-14 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20231103_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='avancement',
            name='contrat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Contrat'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='avancement',
            name='grade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Grade'),
            preserve_default=False,
        ),
    ]
