# Generated by Django 5.1.3 on 2024-11-22 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_affectation_id_alter_categorie_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('jours_utilises', models.PositiveIntegerField(default=0, null=True)),
                ('jours_restants', models.PositiveIntegerField(default=0, null=True)),
                ('employe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.employe')),
            ],
        ),
    ]
